### ISSUE TITLE
Compatible with MW 1.33

### ISSUE THREAD

**Issue by RazeSoldier** [nbdd0121/MW-FlowThread#32]
MediaWiki 1.33 is the latest version, and this extension require compatibility fixes for this version.

### LanguageZh::truncate()
Error message:
```
Error from line 24 of extensions/FlowThread/echo/PresentationModel.php: Call to undefined method LanguageZh::truncate()
```
[mediawiki-core/RELEASE-NOTES-1.33](https://github.com/wikimedia/mediawiki/blob/62dc614600bcb00a556f7295f5c008d04cdc75a9/RELEASE-NOTES-1.33#L244):
```
Language::truncate(), deprecated in 1.31, has been removed.
```

### Title::canTalk()
Error message:
```
PHP Fatal Error from line 165 of extensions/FlowThread/includes/Helper.php: Uncaught Error: Call to undefined method Title::canTalk() in extensions/FlowThread/includes/Helper.php:165
Stack trace:
#0 extensions/FlowThread/includes/Hooks.php(11): FlowThread\Helper::canEverPostOnTitle(Object(Title))
#1 includes/Hooks.php(174): FlowThread\Hooks::onBeforePageDisplay(Object(OutputPage), Object(SkinMinerva))
#2 includes/Hooks.php(234): Hooks::callHook('BeforePageDispl...', Array, Array, NULL, 'FlowThread\\Hook...')
#3 includes/OutputPage.php(2720): Hooks::runWithoutAbort('BeforePageDispl...', Array)
#4 includes/exception/MWExceptionRenderer.php(134): OutputPage->output()
#5 includes/exception/MWExceptionRenderer.php(53): MWExceptionRenderer::reportHTML(Object(Error))
#6 includes/exception/MWExceptionHandler.php(98): MWExceptionRenderer::output(Object(Error), 2)
#7 includes/exception/MWExceptionHandler.php(172): MWExceptionHandler::report(Object(Error))
```
[mediawiki-core/RELEASE-NOTES-1.33](https://github.com/wikimedia/mediawiki/blob/62dc614600bcb00a556f7295f5c008d04cdc75a9/RELEASE-NOTES-1.33#L321):
```
Title->canTalk(), deprecated in 1.30, was removed. Instead, use Title->canHaveTalkPage().
```

**Comment by nbdd0121** [comment]
Hopefully 9aa2e11 resolves your issue

**Comment by RazeSoldier** [comment]
Thank you for your quick fix.
