### ISSUE TITLE
加载评论GET 500错误

### ISSUE THREAD

**Issue by YohoYang** [nbdd0121/MW-FlowThread#43]
### 错误信息

```php
{"error":{"code":"unknown_error","info":"A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? \nQuery: select FOUND_ROWS() as row\nFunction: Wikimedia\\Rdbms\\DBConnRef::query\nError: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'row' at line 1 (localhost)\n"}}
Internal Server Error
[a8f784bf6e8e0406eb5b4f4d] /api.php?action=flowthread&format=json&type=list&pageid=50&offset=0&utf8= Wikimedia\Rdbms\DBTransactionError from line 1680 of /www/wwwroot/*/includes/libs/rdbms/loadbalancer/LoadBalancer.php: MediaWiki::preOutputCommit: Commit failed on server(s) localhost: Cannot execute query from MediaWiki::preOutputCommit while transaction status is ERROR
Backtrace:
#0 /www/wwwroot/*/includes/libs/rdbms/lbfactory/LBFactory.php(208): Wikimedia\Rdbms\LoadBalancer->commitMasterChanges()
#1 /www/wwwroot/*/includes/libs/rdbms/lbfactory/LBFactorySimple.php(134): Wikimedia\Rdbms\LBFactory->Wikimedia\Rdbms\{closure}()
#2 /www/wwwroot/*/includes/libs/rdbms/lbfactory/LBFactory.php(210): Wikimedia\Rdbms\LBFactorySimple->forEachLB()
#3 /www/wwwroot/*/includes/libs/rdbms/lbfactory/LBFactory.php(273): Wikimedia\Rdbms\LBFactory->forEachLBCallMethod()
#4 /www/wwwroot/*/includes/MediaWiki.php(611): Wikimedia\Rdbms\LBFactory->commitMasterChanges()
#5 /www/wwwroot/*/includes/api/ApiMain.php(554): MediaWiki::preOutputCommit()
#6 /www/wwwroot/*/includes/api/ApiMain.php(508): ApiMain->executeActionWithErrorHandling()
#7 /www/wwwroot/*/api.php(87): ApiMain->execute()
#8 {main}
```

# 使用版本

产品  版本
MediaWiki	1.34.1
PHP	7.4.4 (fpm-fcgi)
MySQL	8.0.16
MW-FlowThread  Master or 1.3.2 release

# 其他说明

查阅数据库，评论可以正常发布，但无法读取到评论的内容

**Comment by zoglun** [comment]
装完要跑一遍Update.php更新数据库，参见： https://www.mediawiki.org/wiki/Manual:Update.php

**Comment by YohoYang** [comment]
> 装完要跑一遍Update.php更新数据库，参见： https://www.mediawiki.org/wiki/Manual:Update.php

有运行，在数据库中已经有查询到表以及评论内容，附上运行记录

```bash
    [root@* ~]# php /www/wwwroot/*/maintenance/update.php
    MediaWiki 1.34.1 Updater
    
    Your composer.lock file is up to date with current dependencies!
    Going to run database updates for conanpedia
    Depending on the size of your database this may take a while!
    Abort with control-c in the next five seconds (skip this countdown with --quick) ... 0
    Turning off Content Handler DB fields for this part of upgrade.
    ...have ipb_id field in ipblocks table.
    ...have ipb_expiry field in ipblocks table.
    ...already have interwiki table
    ...indexes seem up to 20031107 standards.
    ...have rc_type field in recentchanges table.
    ...index new_name_timestamp already set on recentchanges table.
    ...have user_real_name field in user table.
    ...querycache table already exists.
    ...objectcache table already exists.
    ...categorylinks table already exists.
    ...have pagelinks; skipping old links table updates
    ...il_from OK
    ...have rc_ip field in recentchanges table.
    ...index PRIMARY already set on image table.
    ...have rc_id field in recentchanges table.
    ...have rc_patrolled field in recentchanges table.
    ...logging table already exists.
    ...have user_token field in user table.
    ...have wl_notificationtimestamp field in watchlist table.
    ...watchlist talk page rows already present.
    ...user table does not contain user_emailauthenticationtimestamp field.
    ...page table already exists.
    ...have log_params field in logging table.
    ...logging table has correct log_title encoding.
    ...have ar_rev_id field in archive table.
    ...have page_len field in page table.
    ...revision table does not contain inverse_timestamp field.
    ...have rev_text_id field in revision table.
    ...have rev_deleted field in revision table.
    ...have img_width field in image table.
    ...have img_metadata field in image table.
    ...have user_email_token field in user table.
    ...have ar_text_id field in archive table.
    ...page_namespace is already a full int (int(11)).
    ...ar_namespace is already a full int (int(11)).
    ...rc_namespace is already a full int (int(11)).
    ...wl_namespace is already a full int (int(11)).
    ...qc_namespace is already a full int (int(11)).
    ...log_namespace is already a full int (int(11)).
    ...have img_media_type field in image table.
    ...already have pagelinks table.
    ...image table does not contain img_type field.
    ...already have unique user_name index.
    ...user_groups table exists and is in current format.
    ...have ss_total_pages field in site_stats table.
    ...user_newtalk table already exists.
    ...have iw_trans field in interwiki table.
    ...wl_notificationtimestamp is already nullable.
    ...index times already set on logging table.
    ...have ipb_range_start field in ipblocks table.
    ...no page_random rows needed to be set
    ...have user_registration field in user table.
    ...templatelinks table already exists
    ...externallinks table already exists.
    ...job table already exists.
    ...have ss_images field in site_stats table.
    ...langlinks table already exists.
    ...querycache_info table already exists.
    ...filearchive table already exists.
    ...have ipb_anon_only field in ipblocks table.
    ...have user_newpass_time field in user table.
    ...redirect table already exists.
    ...querycachetwo table already exists.
    ...have ipb_enable_autoblock field in ipblocks table.
    ...index pl_namespace on table pagelinks includes field pl_from.
    ...index tl_namespace on table templatelinks includes field tl_from.
    ...index il_to on table imagelinks includes field il_from.
    ...have rc_old_len field in recentchanges table.
    ...have user_editcount field in user table.
    ...page_restrictions table already exists.
    ...have log_id field in logging table.
    ...have rev_parent_id field in revision table.
    ...have pr_id field in page_restrictions table.
    ...have rev_len field in revision table.
    ...have rc_deleted field in recentchanges table.
    ...have log_deleted field in logging table.
    ...have ar_deleted field in archive table.
    ...have ipb_deleted field in ipblocks table.
    ...have fa_deleted field in filearchive table.
    ...have ar_len field in archive table.
    ...have ipb_block_email field in ipblocks table.
    ...index cl_sortkey on table categorylinks includes field cl_from.
    ...have oi_metadata field in oldimage table.
    ...have ar_page_id field in archive table.
    ...have img_sha1 field in image table.
    ...protected_titles table already exists.
    ...page_props table already exists.
    ...updatelog table already exists.
    ...category table already exists.
    ...category table already populated.
    ...have ar_parent_id field in archive table.
    ...have user_last_timestamp field in user_newtalk table.
    ...protected_titles table has correct pt_title encoding.
    ...have ss_active_users field in site_stats table.
    ...ss_active_users user count set...
    ...have ipb_allow_usertalk field in ipblocks table.
    ...change_tag table already exists.
    ...user_properties table already exists.
    ...log_search table already exists.
    ...l10n_cache table already exists.
    ...ct_rc_id key doesn't exist.
    ...have rd_interwiki field in redirect table.
    ...*_mime_minor fields are already long enough.
    ...iwlinks table already exists.
    ...index iwl_prefix_title_from already set on iwlinks table.
    ...have ul_value field in updatelog table.
    ...have iw_api field in interwiki table.
    ...iwl_prefix key doesn't exist.
    ...have cl_collation field in categorylinks table.
    ...categorylinks up-to-date.
    ...module_deps table already exists.
    ...ar_page_revid key doesn't exist.
    ...skipping index ar_revid because index ar_revid_uniq already set on archive table.
    ...ll_lang is up-to-date.
    ...user_last_timestamp is already nullable.
    ...index user_email already set on user table.
    ...up_property in table user_properties already modified by patch patch-up_property.sql.
    ...uploadstash table already exists.
    ...user_former_groups table already exists.
    ...have rev_sha1 field in revision table.
    ...batch conversion of user_options: nothing to migrate. done.
    ...user table does not contain user_options field.
    ...have ar_sha1 field in archive table.
    ...index page_redirect_namespace_len already set on page table.
    ...have us_chunk_inx field in uploadstash table.
    ...have job_timestamp field in job table.
    ...index page_user_timestamp already set on revision table.
    ...have ipb_parent_block_id field in ipblocks table.
    ...index ipb_parent_block_id already set on ipblocks table.
    ...category table does not contain cat_hidden field.
    ...have rev_content_format field in revision table.
    ...have rev_content_model field in revision table.
    ...have ar_content_format field in archive table.
    ...have ar_content_model field in archive table.
    ...have page_content_model field in page table.
    Content Handler DB fields should be usable now.
    ...site_stats table does not contain ss_admins field.
    ...recentchanges table does not contain rc_moved_to_title field.
    ...sites table already exists.
    ...have fa_sha1 field in filearchive table.
    ...have job_token field in job table.
    ...have job_attempts field in job table.
    ...have us_props field in uploadstash table.
    ...ug_group in table user_groups already modified by patch patch-ug_group-length-increase-255.sql.
    ...ufg_group in table user_former_groups already modified by patch patch-ufg_group-length-increase-255.sql.
    ...index pp_propname_page already set on page_props table.
    ...index img_media_mime already set on image table.
    ...iwl_prefix_title_from index is already non-UNIQUE.
    ...index iwl_prefix_from_title already set on iwlinks table.
    ...have ar_id field in archive table.
    ...have el_id field in externallinks table.
    ...have rc_source field in recentchanges table.
    ...have page_links_updated field in page table.
    ...have user_password_expires field in user table.
    ...have pp_sortkey field in page_props table.
    ...recentchanges table does not contain rc_cur_time field.
    ...index wl_user_notificationtimestamp already set on watchlist table.
    ...have page_lang field in page table.
    ...have pl_from_namespace field in pagelinks table.
    ...have tl_from_namespace field in templatelinks table.
    ...have il_from_namespace field in imagelinks table.
    ...img_major_mime in table image already modified by patch patch-img_major_mime-chemical.sql.
    ...oi_major_mime in table oldimage already modified by patch patch-oi_major_mime-chemical.sql.
    ...fa_major_mime in table filearchive already modified by patch patch-fa_major_mime-chemical.sql.
    ...comment fields are up to date.
    ...hitcounter doesn't exist.
    ...site_stats table does not contain ss_total_views field.
    ...page table does not contain page_counter field.
    ...msg_resource_links doesn't exist.
    ...msg_resource doesn't exist.
    ...bot_passwords table already exists.
    ...have wl_id field in watchlist table.
    ...cl_collation key doesn't exist.
    ...index cl_collation_ext already set on categorylinks table.
    ...collations up-to-date.
    ...index rc_name_type_patrolled_timestamp already set on recentchanges table.
    ...rev_page_id index already non-unique.
    ...pl_namespace, tl_namespace, il_to indices are already non-UNIQUE.
    ...have ct_id field in change_tag table.
    ...rc_ip in table recentchanges already modified by patch patch-rc_ip_modify.sql.
    ...have el_index_60 field in externallinks table.
    ...ug_user_group key doesn't exist.
    ...have ug_expiry field in user_groups table.
    ...img_media_type in table image already modified by patch patch-add-3d.sql.
    ...ip_changes table already exists.
    ...index PRIMARY already set on categorylinks table.
    ...index PRIMARY already set on templatelinks table.
    ...index PRIMARY already set on pagelinks table.
    ...index PRIMARY already set on text table.
    ...index PRIMARY already set on imagelinks table.
    ...index PRIMARY already set on iwlinks table.
    ...index PRIMARY already set on langlinks table.
    ...index PRIMARY already set on log_search table.
    ...index PRIMARY already set on module_deps table.
    ...index PRIMARY already set on objectcache table.
    ...index PRIMARY already set on querycache_info table.
    ...index PRIMARY already set on site_stats table.
    ...index PRIMARY already set on user_former_groups table.
    ...index PRIMARY already set on user_properties table.
    ...comment table already exists.
    ...revision_comment_temp table already exists.
    ...have ar_comment_id field in archive table.
    ...have fa_description_id field in filearchive table.
    ...img_description field does not exist in image table, skipping modify field patch.
    ...have ipb_reason_id field in ipblocks table.
    ...have log_comment_id field in logging table.
    ...have oi_description_id field in oldimage table.
    ...have pt_reason_id field in protected_titles table.
    ...have rc_comment_id field in recentchanges table.
    ...rev_comment in table revision already modified by patch patch-revision-rev_comment-default.sql.
    ...have img_description_id field in image table.
    ...index PRIMARY already set on l10n_cache table.
    ...bot_passwords.bp_user is already unsigned int.
    ...change_tag.ct_log_id is already unsigned int.
    ...change_tag.ct_rev_id is already unsigned int.
    ...page_restrictions.pr_user is already unsigned int.
    ...user_newtalk.user_id is already unsigned int.
    ...user_properties.up_user is already unsigned int.
    ...slots table already exists.
    ...have slot_origin field in slots table.
    ...content table already exists.
    ...slot_roles table already exists.
    ...content_models table already exists.
    ...actor table already exists.
    ...revision_actor_temp table already exists.
    ...have ar_actor field in archive table.
    ...have ipb_by_actor field in ipblocks table.
    ...have img_actor field in image table.
    ...have oi_actor field in oldimage table.
    ...have fa_actor field in filearchive table.
    ...have rc_actor field in recentchanges table.
    ...have log_actor field in logging table.
    ...rev_text_id in table revision already modified by patch patch-rev_text_id-default.sql.
    ...table site_stats already modified by patch patch-site_stats-modify.sql.
    ...index rc_namespace_title_timestamp already set on recentchanges table.
    ...change_tag_def table already exists.
    ...el_index_60 in table externallinks already modified by patch patch-externallinks-el_index_60-drop-default.sql.
    Running maintenance/deduplicateArchiveRevId.php...
    ...Update 'DeduplicateArchiveRevId' already logged as completed. Use --force to run it again.
    done.
    ...have ct_tag_id field in change_tag table.
    ...index ar_revid_uniq already set on archive table.
    ...index log_type_action already set on logging table.
    ...type_action key doesn't exist.
    ...index PRIMARY already set on interwiki table.
    ...index PRIMARY already set on page_props table.
    ...index PRIMARY already set on protected_titles table.
    ...index PRIMARY already set on site_identifiers table.
    ...index rc_this_oldid already set on recentchanges table.
    ...transcache doesn't exist.
    Running maintenance/populateChangeTagDef.php...
    ...Update 'PopulateChangeTagDef' already logged as completed. Use --force to run it again.
    done.
    ...index change_tag_rc_tag_id already set on change_tag table.
    ...have ipb_sitewide field in ipblocks table.
    ...ipblocks_restrictions table already exists.
    ...change_tag table does not contain ct_tag field.
    ...valid_tag doesn't exist.
    ...tag_summary doesn't exist.
    ...protected_titles table does not contain pt_reason field.
    ...table job already modified by patch patch-job-params-mediumblob.sql.
    ...ar_usertext_timestamp key doesn't exist.
    ...usertext_timestamp key doesn't exist.
    ...logging table does not contain log_user field.
    ...index un_user_ip already set on user_newtalk table.
    ...echo_event table already exists.
    ...echo_email_batch table already exists.
    ...echo_target_page table already exists.
    ...event_agent field does not exist in echo_event table, skipping modify field patch.
    ...event_variant in table echo_event already modified by patch /www/wwwroot/*/extensions/Echo/db_patches/patch-event_variant_nullability.sql.
    ...event_extra in table echo_event already modified by patch /www/wwwroot/*/extensions/Echo/db_patches/patch-event_extra-size.sql.
    ...event_agent_ip in table echo_event already modified by patch /www/wwwroot/*/extensions/Echo/db_patches/patch-event_agent_ip-size.sql.
    ...have etp_id field in echo_target_page table.
    ...echo_target_page table does not contain etp_user field.
    ...have notification_bundle_hash field in echo_notification table.
    ...echo_subscription doesn't exist.
    ...echo_event table does not contain event_timestamp field.
    ...have eeb_event_hash field in echo_email_batch table.
    ...have event_page_id field in echo_event table.
    ...index echo_event_type already set on echo_event table.
    ...index echo_user_timestamp already set on echo_notification table.
    ...index echo_notification_event already set on echo_notification table.
    ...have event_deleted field in echo_event table.
    ...index echo_notification_user_read_timestamp already set on echo_notification table.
    ...index echo_target_page_page_event already set on echo_target_page table.
    ...index echo_event_page_id already set on echo_event table.
    ...user_event key doesn't exist.
    Running extensions/Echo/maintenance/updateEchoSchemaForSuppression.php...
    ...Update 'UpdateEchoSchemaForSuppression' already logged as completed. Use --force to run it again.
    done.
    ...echo_event table does not contain event_page_namespace field.
    ...echo_event table does not contain event_page_title field.
    ...echo_notification table does not contain notification_bundle_base field.
    ...echo_notification table does not contain notification_bundle_display_hash field.
    ...echo_notification_user_hash_timestamp key doesn't exist.
    Creating FlowThread table ...done.
    ...FlowThreadAttitude table already exists.
    Creating FlowThreadControl table ...done.
    ...site_stats is populated...done.
    ...Update 'populate rev_len and ar_len' already logged as completed. Use --force to run it again.
    ...Update 'populate rev_sha1' already logged as completed. Use --force to run it again.
    ...img_sha1 column of image table already populated.
    ...protocol-relative URLs in externallinks table already fixed.
    ...fa_sha1 column of filearchive table already populated.
    ...*_from_namespace column of backlink tables already populated.
    ...Update 'FixDefaultJsonContentPages' already logged as completed. Use --force to run it again.
    ...Update 'cleanup empty categories' already logged as completed. Use --force to run it again.
    ...RFC and PMID already added to interwiki database table.
    ...Update 'populate pp_sortkey' already logged as completed. Use --force to run it again.
    ...Update 'populate ip_changes' already logged as completed. Use --force to run it again.
    ...externallinks table indexes up to date
    ...Update 'RemoveOrphanedEvents' already logged as completed. Use --force to run it again.
    Set the local repo temp zone container to be private.
    Purging caches...done.
    
    Done in 0.8 s.
    
```

**Comment by nbdd0121** [comment]
不是MySQL？是什么数据库？

**Comment by YohoYang** [comment]
> 不是MySQL？是什么数据库？

是MySQL 8.0.16

**Comment by zoglun** [comment]
那我就不知道是什么问题了，BTW提醒下 https://www.mediawiki.org/wiki/Compatibility

Mediawiki目前master branch， mysql支持版本还在MySQL 5.5.8+。生产环境证实可跑的有5.5，5.6。测试环境5.7未出错，8.0条目内容丢失。 不针对这个插件，你可能需要降MySQL版本，Mediawiki本身对8.0有兼容性问题。

**Comment by YohoYang** [comment]
> 那我就不知道是什么问题了，BTW提醒下 https://www.mediawiki.org/wiki/Compatibility
> 
> Mediawiki目前master branch， mysql支持版本还在MySQL 5.5.8+。生产环境证实可跑的有5.5，5.6。测试环境5.7未出错，8.0条目内容丢失。 不针对这个插件，你可能需要降MySQL版本，Mediawiki本身对8.0有兼容性问题。

啊，可能就是版本太高的问题吧，了解了，谢谢提醒

**Comment by RazeSoldier** [comment]
FYI,10.3的mariadb没有问题
